import type { Talent } from "@/lib/types";

export const dummyTalents: Talent[] = [
  {
    id: "t1",
    firstName: "Max",
    lastName: "Keller",
    birthDate: "2008-02-14",
    primaryPosition: "IV",
    secondaryPosition: null,
    clubNameText: "VfB Musterstadt",
    teamNameText: "U17",
    leagueText: "A-Junioren Regionalliga",
    countryText: "Deutschland",
    contractStatus: "auslaufend",
    contractEndDate: "2026-06-30",
    status: "in_beobachtung",
    isMinor: true,
    visibilityStatus: "freigegeben",
    archived_at: null,
    currentAlert: {
      id: "a1",
      talentId: "t1",
      riskLevel: "gelb",
      riskScore: 62,
      triggeredReasons: ["Konstante Entwicklung", "Gute Kopfballwerte"],
      isHiddenGem: false,
      calculatedAt: "2026-07-31T00:00:00.000Z",
    },
    lastReportDate: "2026-07-21",
  },
  {
    id: "t2",
    firstName: "Leon",
    lastName: "Weber",
    birthDate: "2006-09-03",
    primaryPosition: "ZOM",
    secondaryPosition: "LA",
    clubNameText: "SV Beispiel",
    teamNameText: "U19",
    leagueText: "A-Junioren Bundesliga",
    countryText: "Deutschland",
    contractStatus: "aktiv",
    contractEndDate: null,
    status: "empfehlung",
    isMinor: true,
    visibilityStatus: "freigegeben",
    archived_at: null,
    currentAlert: {
      id: "a2",
      talentId: "t2",
      riskLevel: "gruen",
      riskScore: 84,
      triggeredReasons: ["Starke Spielintelligenz", "Hohe Passqualität"],
      isHiddenGem: true,
      calculatedAt: "2026-07-31T00:00:00.000Z",
    },
    lastReportDate: "2026-07-28",
  },
  {
    id: "t3",
    firstName: "Noah",
    lastName: "Schmidt",
    birthDate: "2004-11-19",
    primaryPosition: "ST",
    secondaryPosition: null,
    clubNameText: "FC Demo",
    teamNameText: "U21",
    leagueText: "Regionalliga",
    countryText: "Deutschland",
    contractStatus: "vereinslos",
    contractEndDate: null,
    status: "verloren",
    isMinor: false,
    visibilityStatus: "privat",
    archived_at: null,
    currentAlert: {
      id: "a3",
      talentId: "t3",
      riskLevel: "rot",
      riskScore: 41,
      triggeredReasons: ["Vertrag ausgelaufen", "Wenige Einsätze"],
      isHiddenGem: false,
      calculatedAt: "2026-07-31T00:00:00.000Z",
    },
    lastReportDate: "2026-07-10",
  },
];

export const dummyWatchlists = [
  {
    id: "w1",
    name: "Top-Talente U19",
    description: "Beobachtung der stärksten U19-Spieler",
    talentCount: 12,
  },
  {
    id: "w2",
    name: "Regionalliga Nord",
    description: "Regionale Watchlist für schnelle Entwicklung",
    talentCount: 8,
  },
];

export const dummyImportHistory = [
  {
    id: "i1",
    sourceFilename: "talente_juli.csv",
    status: "abgeschlossen",
    totalRows: 24,
    importedRows: 24,
    errorRows: 0,
    startedAt: "2026-07-29T10:15:00.000Z",
  },
  {
    id: "i2",
    sourceFilename: "scouting_verein.xlsx",
    status: "teilweise_fehlgeschlagen",
    totalRows: 18,
    importedRows: 15,
    errorRows: 3,
    startedAt: "2026-07-30T14:20:00.000Z",
  },
];
