// Dummy-Daten für die erste Version des Frontends.
// Sobald die Server Actions aus dem technischen Umsetzungsplan angebunden sind,
// werden diese Funktionen durch echte Supabase-Queries ersetzt — die
// Rückgabetypen (siehe lib/types.ts) bleiben dabei identisch, damit die
// Seiten selbst nicht angepasst werden müssen.

import type {
  Talent,
  Reminder,
  Watchlist,
  ScoutReport,
  ImportJobPreview,
} from "./types";

export const dummyTalents: Talent[] = [
  {
    id: "t1",
    firstName: "Max",
    lastName: "Keller",
    birthDate: "2009-03-14",
    primaryPosition: "IV",
    secondaryPosition: null,
    clubNameText: "FC Beispiel",
    teamNameText: "U17",
    leagueText: "Regionalliga Süd",
    countryText: "Deutschland",
    contractStatus: "auslaufend",
    contractEndDate: "2027-06-30",
    status: "in_beobachtung",
    isMinor: true,
    visibilityStatus: "privat",
    lastReportDate: "2026-04-17",
    archivedAt: null,
    updatedAt: "2026-04-17T09:30:00Z",
    currentAlert: {
      id: "a1",
      talentId: "t1",
      riskLevel: "rot",
      riskScore: 100,
      isHiddenGem: true,
      triggeredReasons: [
        "Kein Bericht seit 95 Tagen",
        "Vertrag läuft in 60 Tagen aus",
        "Ø-Rating der letzten 3 Berichte: 4,3",
      ],
      calculatedAt: "2026-07-20",
    },
  },
  {
    id: "t2",
    firstName: "Timur",
    lastName: "Aydin",
    birthDate: "2010-08-02",
    primaryPosition: "ST",
    secondaryPosition: null,
    clubNameText: "SV Muster",
    teamNameText: "U16",
    leagueText: "Bezirksliga",
    countryText: "Deutschland",
    contractStatus: "unbekannt",
    status: "in_beobachtung",
    isMinor: true,
    visibilityStatus: "privat",
    lastReportDate: "2026-06-10",
    archivedAt: null,
    updatedAt: "2026-06-10T14:00:00Z",
    currentAlert: {
      id: "a2",
      talentId: "t2",
      riskLevel: "rot",
      riskScore: 70,
      isHiddenGem: false,
      triggeredReasons: [
        "Kein Bericht seit 40 Tagen (U16-Schwelle: 60 Tage überschritten in Kürze)",
        "Wiedervorlage überfällig",
      ],
      calculatedAt: "2026-07-20",
    },
  },
  {
    id: "t3",
    firstName: "Jonas",
    lastName: "Brandt",
    birthDate: "2007-11-23",
    primaryPosition: "TW",
    secondaryPosition: null,
    clubNameText: "TSV Nordstadt",
    teamNameText: "U19",
    leagueText: "Landesliga",
    countryText: "Deutschland",
    contractStatus: "auslaufend",
    contractEndDate: "2026-12-31",
    status: "in_beobachtung",
    isMinor: false,
    visibilityStatus: "freigegeben",
    lastReportDate: "2026-05-12",
    archivedAt: null,
    updatedAt: "2026-05-12T11:15:00Z",
    currentAlert: {
      id: "a3",
      talentId: "t3",
      riskLevel: "gelb",
      riskScore: 45,
      isHiddenGem: false,
      triggeredReasons: ["Vertrag läuft in 5 Monaten aus"],
      calculatedAt: "2026-07-20",
    },
  },
  {
    id: "t4",
    firstName: "Sina",
    lastName: "Weiss",
    birthDate: "2011-01-30",
    primaryPosition: "DM",
    secondaryPosition: null,
    clubNameText: "FC Talberg",
    teamNameText: "U15",
    leagueText: null,
    countryText: "Deutschland",
    contractStatus: "aktiv",
    contractEndDate: null,
    status: "in_beobachtung",
    isMinor: true,
    visibilityStatus: "privat",
    lastReportDate: "2026-07-01",
    archivedAt: null,
    updatedAt: "2026-07-01T16:45:00Z",
    currentAlert: {
      id: "a4",
      talentId: "t4",
      riskLevel: "gelb",
      riskScore: 35,
      isHiddenGem: false,
      triggeredReasons: [
        "Aufwärtstrend über die letzten 3 Berichte erkannt (Late-Bloomer-Signal)",
      ],
      calculatedAt: "2026-07-20",
    },
  },
  {
    id: "t5",
    firstName: "Leon",
    lastName: "Fischer",
    birthDate: "2008-05-19",
    primaryPosition: "RM",
    secondaryPosition: null,
    clubNameText: "VfB Ostend",
    teamNameText: "U18",
    leagueText: null,
    countryText: "Deutschland",
    contractStatus: "aktiv",
    contractEndDate: null,
    status: "empfehlung",
    isMinor: false,
    visibilityStatus: "freigegeben",
    lastReportDate: "2026-07-15",
    archivedAt: null,
    updatedAt: "2026-07-15T10:00:00Z",
    currentAlert: {
      id: "a5",
      talentId: "t5",
      riskLevel: "gruen",
      riskScore: 8,
      isHiddenGem: false,
      triggeredReasons: [],
      calculatedAt: "2026-07-20",
    },
  },
];

export const dummyReports: Record<string, ScoutReport[]> = {
  t1: [
    {
      id: "r1",
      talentId: "t1",
      authorName: "M. Gruber",
      matchDate: "2026-04-17",
      opponent: "SC Nachbarort",
      scoreTechnik: 4,
      scoreTaktik: 5,
      scoreAthletik: 4,
      scoreMentalitaet: 4,
      overallRating: 4.3,
      overallRatingSource: "calculated",
      comment:
        "Sehr ruhiger Spielaufbau, gewinnt die meisten Zweikämpfe antizipativ statt durch Zweikampfstärke.",
      createdAt: "2026-04-17",
    },
    {
      id: "r0",
      talentId: "t1",
      authorName: "M. Gruber",
      matchDate: "2026-02-02",
      opponent: "FC Talberg",
      scoreTechnik: 4,
      scoreTaktik: 4,
      scoreAthletik: 3,
      scoreMentalitaet: 4,
      overallRating: 3.8,
      overallRatingSource: "calculated",
      comment:
        "Solide Leistung, körperlich noch im Rückstand zu direkten Gegenspielern.",
      createdAt: "2026-02-02",
    },
  ],
};

export const dummyReminders: Reminder[] = [
  {
    id: "rm1",
    talentId: "t1",
    talentName: "Max Keller",
    dueDate: "2026-07-17",
    reason: "Automatisch: Alert-Level Rot",
    status: "ueberfaellig",
    isSystemGenerated: true,
  },
  {
    id: "rm2",
    talentId: "t2",
    talentName: "Timur Aydin",
    dueDate: "2026-07-20",
    reason: "Rückkehr nach Verletzungspause prüfen",
    status: "offen",
    isSystemGenerated: false,
  },
  {
    id: "rm3",
    talentId: "t3",
    talentName: "Jonas Brandt",
    dueDate: "2026-07-25",
    reason: "Standard-Re-Scouting (90-Tage-Intervall)",
    status: "offen",
    isSystemGenerated: true,
  },
];

export const dummyWatchlists: Watchlist[] = [
  {
    id: "w1",
    name: "U17-Kader Sommer-Turnier",
    description: "Kandidaten für das Einladungsturnier im August",
    talentCount: 8,
  },
  {
    id: "w2",
    name: "Rückrunde-Fokus",
    description: null,
    talentCount: 5,
  },
  {
    id: "w3",
    name: "Torhüter-Beobachtung 2026",
    description: "Gezielte TW-Sichtung über die Saison",
    talentCount: 3,
  },
];

export const dummyImportHistory: ImportJobPreview[] = [
  {
    id: "i1",
    sourceFilename: "scouting_liste_2026_q2.xlsx",
    status: "teilweise_fehlgeschlagen",
    totalRows: 250,
    importedRows: 248,
    errorRows: 2,
    startedAt: "2026-07-12",
  },
  {
    id: "i2",
    sourceFilename: "nachwuchs_uebersicht.csv",
    status: "abgeschlossen",
    totalRows: 112,
    importedRows: 112,
    errorRows: 0,
    startedAt: "2026-06-03",
  },
];

export function getTalentById(id: string): Talent | undefined {
  return dummyTalents.find((t) => t.id === id);
}
